/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calendar.apis;

public class Callback {

    // bruhhhhh
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CalendarService testCalendar = new CalendarService();
        try {
            testCalendar.test();
        } catch (Exception e) {
            // System.out.println("You are an error.");
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }
}
